#ifndef QUARIABLE_DEFINES
#define QUARIABLE_DEFINES

#define DEFAULT_PREDICATE_NAME QString()
#define DEFAULT_ITEMS_LIMIT 5000
#define DEFAULT_REQUESTS_LIMIT 25

#define IGNORE_PARAM -1

#define OFFSET_TEMPLATE QStringLiteral("^1")
//#define LIMIT_TEMPLATE QStringLiteral("^2")

#endif // QUARIABLE_DEFINES
