#ifndef QUARIABLE_DEFINES
#define QUARIABLE_DEFINES

#define DEFAULT_PREDICATE_NAME QString()
#define DEFAULT_ITEMS_LIMIT 10000
#define DEFAULT_REQUESTS_LIMIT 2

#define IGNORE_PARAM -1

#define OFFSET_TEMPLATE QLatin1String("^1")
#define OFFSET_TEMPLATE_ENC QUrl::toPercentEncoding(OFFSET_TEMPLATE)
//#define LIMIT_TEMPLATE QLatin1String("^2")

#endif // QUARIABLE_DEFINES
