#ifndef HOTKEY_TYPES_H
#define HOTKEY_TYPES_H

#define HOTKEY_NEXT 1
#define HOTKEY_NEXT_AND_DELETE 2
#define HOTKEY_PREV 3
#define HOTKEY_PLAY 4
#define HOTKEY_STOP 5
#define HOTKEY_SETTINGS 6
//#define HOTKEY_ADD_ENTITES 7
#define HOTKEY_POS_SLIDE_FORWARD 8
#define HOTKEY_POS_SLIDE_BACKWARD 9
#define HOTKEY_VOL_SLIDE_FORWARD 10
#define HOTKEY_VOL_SLIDE_BACKWARD 11
//#define HOTKEY_MOVE_TO_PLAYLIST 12

#endif // HOTKEY_TYPES_H
