#include "id3_music_genres.h"

using namespace Core::Media;

void Id3MusicGenres::initDefault() {
    genres.insert(QLatin1String("blues"), 0);
    genres.insert(QLatin1String("classic rock"), 1);
    genres.insert(QLatin1String("country"), 2);
    genres.insert(QLatin1String("dance"), 3);
    genres.insert(QLatin1String("disco"), 4);
    genres.insert(QLatin1String("funk"), 5);
    genres.insert(QLatin1String("grunge"), 6);
    genres.insert(QLatin1String("hip hop"), 7);
    genres.insert(QLatin1String("jazz"), 8);
    genres.insert(QLatin1String("metal"), 9);
    genres.insert(QLatin1String("new age"), 10);
    genres.insert(QLatin1String("oldies"), 11);
    genres.insert(QLatin1String("other"), 12);
    genres.insert(QLatin1String("pop"), 13);
    genres.insert(QLatin1String("rhythm & blues"), 14);
    genres.insert(QLatin1String("rhythm and blues"), 14);
    genres.insert(QLatin1String("rap"), 15);
    genres.insert(QLatin1String("reggae"), 16);
    genres.insert(QLatin1String("rock"), 17);
    genres.insert(QLatin1String("techno"), 18);
    genres.insert(QLatin1String("industrial"), 19);
    genres.insert(QLatin1String("alternative"), 20);
    genres.insert(QLatin1String("ska"), 21);
    genres.insert(QLatin1String("death metal"), 22);
    genres.insert(QLatin1String("pranks"), 23);
    genres.insert(QLatin1String("soundtrack"), 24);
    genres.insert(QLatin1String("euro techno"), 25);
    genres.insert(QLatin1String("ambient"), 26);
    genres.insert(QLatin1String("trip hop"), 27);
    genres.insert(QLatin1String("trip"), 27);
    genres.insert(QLatin1String("vocal"), 28);
    genres.insert(QLatin1String("jazz & funk"), 29);
    genres.insert(QLatin1String("jazz and funk"), 29);
    genres.insert(QLatin1String("fusion"), 30);
    genres.insert(QLatin1String("trance"), 31);
    genres.insert(QLatin1String("classical"), 32);
    genres.insert(QLatin1String("instrumental"), 33);
    genres.insert(QLatin1String("acid"), 34);
    genres.insert(QLatin1String("house"), 35);
    genres.insert(QLatin1String("game"), 36);
    genres.insert(QLatin1String("sound clip"), 37);
    genres.insert(QLatin1String("gospel"), 38);
    genres.insert(QLatin1String("noise"), 39);
    genres.insert(QLatin1String("alternative rock"), 40);
    genres.insert(QLatin1String("bass"), 41);
    genres.insert(QLatin1String("soul"), 42);
    genres.insert(QLatin1String("punk"), 43);
    genres.insert(QLatin1String("space"), 44);
    genres.insert(QLatin1String("meditative"), 45);
    genres.insert(QLatin1String("instrumental pop"), 46);
    genres.insert(QLatin1String("instrumental rock"), 47);
    genres.insert(QLatin1String("ethnic"), 48);
    genres.insert(QLatin1String("gothic"), 49);
    genres.insert(QLatin1String("darkwave"), 50);
    genres.insert(QLatin1String("techno industrial"), 51);
    genres.insert(QLatin1String("electronic"), 52);
    genres.insert(QLatin1String("pop folk"), 53);
    genres.insert(QLatin1String("eurodance"), 54);
    genres.insert(QLatin1String("dream"), 55);
    genres.insert(QLatin1String("southern rock"), 56);
    genres.insert(QLatin1String("comedy"), 57);
    genres.insert(QLatin1String("cult"), 58);
    genres.insert(QLatin1String("gangsta"), 59);
    genres.insert(QLatin1String("top 40"), 60);
    genres.insert(QLatin1String("christian rap"), 61);
    genres.insert(QLatin1String("pop funk"), 62);
    genres.insert(QLatin1String("jungle"), 63);
    genres.insert(QLatin1String("native american"), 64);
    genres.insert(QLatin1String("cabaret"), 65);
    genres.insert(QLatin1String("new wave"), 66);
    genres.insert(QLatin1String("psychedelic"), 67);
    genres.insert(QLatin1String("rave"), 68);
    genres.insert(QLatin1String("showtunes"), 69);
    genres.insert(QLatin1String("trailer"), 70);
    genres.insert(QLatin1String("lo fi"), 71);
    genres.insert(QLatin1String("tribal"), 72);
    genres.insert(QLatin1String("acid punk"), 73);
    genres.insert(QLatin1String("acid jazz"), 74);
    genres.insert(QLatin1String("polka"), 75);
    genres.insert(QLatin1String("retro"), 76);
    genres.insert(QLatin1String("musical"), 77);
    genres.insert(QLatin1String("rock & roll"), 78);
    genres.insert(QLatin1String("rock and roll"), 78);
    genres.insert(QLatin1String("hard rock"), 79);
    genres.insert(QLatin1String("folk"), 80);
    genres.insert(QLatin1String("folk rock"), 81);
    genres.insert(QLatin1String("national folk"), 82);
    genres.insert(QLatin1String("swing"), 83);
    genres.insert(QLatin1String("fast fusion"), 84);
    genres.insert(QLatin1String("bebop"), 85);
    genres.insert(QLatin1String("latin"), 86);
    genres.insert(QLatin1String("revival"), 87);
    genres.insert(QLatin1String("celtic"), 88);
    genres.insert(QLatin1String("bluegrass"), 89);
    genres.insert(QLatin1String("avantgarde"), 90);
    genres.insert(QLatin1String("gothic rock"), 91);
    genres.insert(QLatin1String("progressive rock"), 92);
    genres.insert(QLatin1String("psychedelic rock"), 93);
    genres.insert(QLatin1String("symphonic rock"), 94);
    genres.insert(QLatin1String("slow rock"), 95);
    genres.insert(QLatin1String("big band"), 96);
    genres.insert(QLatin1String("chorus"), 97);
    genres.insert(QLatin1String("easy listening"), 98);
    genres.insert(QLatin1String("acoustic"), 99);
    genres.insert(QLatin1String("humour"), 100);
    genres.insert(QLatin1String("speech"), 101);
    genres.insert(QLatin1String("chanson"), 102);
    genres.insert(QLatin1String("opera"), 103);
    genres.insert(QLatin1String("chamber music"), 104);
    genres.insert(QLatin1String("sonata"), 105);
    genres.insert(QLatin1String("symphony"), 106);
    genres.insert(QLatin1String("booty bass"), 107);
    genres.insert(QLatin1String("primus"), 108);
    genres.insert(QLatin1String("porn groove"), 109);
    genres.insert(QLatin1String("satire"), 110);
    genres.insert(QLatin1String("slow jam"), 111);
    genres.insert(QLatin1String("club"), 112);
    genres.insert(QLatin1String("tango"), 113);
    genres.insert(QLatin1String("samba"), 114);
    genres.insert(QLatin1String("folklore"), 115);
    genres.insert(QLatin1String("ballad"), 116);
    genres.insert(QLatin1String("power ballad"), 117);
    genres.insert(QLatin1String("rhythmic soul"), 118);
    genres.insert(QLatin1String("freestyle"), 119);
    genres.insert(QLatin1String("duet"), 120);
    genres.insert(QLatin1String("punk rock"), 121);
    genres.insert(QLatin1String("drum solo"), 122);
    genres.insert(QLatin1String("a capella"), 123);
    genres.insert(QLatin1String("acapella"), 123);
    genres.insert(QLatin1String("euro house"), 124);
    genres.insert(QLatin1String("dance hall"), 125);
    genres.insert(QLatin1String("goa"), 126);
    genres.insert(QLatin1String("drum & bass"), 127);
    genres.insert(QLatin1String("drum and bass"), 127);
    genres.insert(QLatin1String("club house"), 128);
    genres.insert(QLatin1String("hardcore techno"), 129);
    genres.insert(QLatin1String("terror"), 130);
    genres.insert(QLatin1String("indie"), 131);
    genres.insert(QLatin1String("britPop"), 132);
    genres.insert(QLatin1String("afro punk"), 133);
    genres.insert(QLatin1String("polsk punk"), 134);
    genres.insert(QLatin1String("beat"), 135);
    genres.insert(QLatin1String("christian gangsta rap"), 136);
    genres.insert(QLatin1String("heavy metal"), 137);
    genres.insert(QLatin1String("black metal"), 138);
    genres.insert(QLatin1String("crossover"), 139);
    genres.insert(QLatin1String("contemporary christian"), 140);
    genres.insert(QLatin1String("christian rock"), 141);
    genres.insert(QLatin1String("merengue"), 142);
    genres.insert(QLatin1String("salsa"), 143);
    genres.insert(QLatin1String("thrash metal"), 144);
    genres.insert(QLatin1String("anime"), 145);
    genres.insert(QLatin1String("jpop"), 146);
    genres.insert(QLatin1String("synthpop"), 147);
    genres.insert(QLatin1String("abstract"), 148);
    genres.insert(QLatin1String("art rock"), 149);
    genres.insert(QLatin1String("baroque"), 150);
    genres.insert(QLatin1String("bhangra"), 151);
    genres.insert(QLatin1String("big beat"), 152);
    genres.insert(QLatin1String("breakbeat"), 153);
    genres.insert(QLatin1String("chillout"), 154);
    genres.insert(QLatin1String("downtempo"), 155);
    genres.insert(QLatin1String("dub"), 156);
    genres.insert(QLatin1String("ebm"), 157);
    genres.insert(QLatin1String("eclectic"), 158);
    genres.insert(QLatin1String("electro"), 159);
    genres.insert(QLatin1String("electroclash"), 160);
    genres.insert(QLatin1String("emo"), 161);
    genres.insert(QLatin1String("experimental"), 162);
    genres.insert(QLatin1String("garage"), 163);
    genres.insert(QLatin1String("global"), 164);
    genres.insert(QLatin1String("idm"), 165);
    genres.insert(QLatin1String("illbient"), 166);
    genres.insert(QLatin1String("industro Goth"), 167);
    genres.insert(QLatin1String("jam band"), 168);
    genres.insert(QLatin1String("krautrock"), 169);
    genres.insert(QLatin1String("leftfield"), 170);
    genres.insert(QLatin1String("lounge"), 171);
    genres.insert(QLatin1String("math rock"), 172);
    genres.insert(QLatin1String("new romantic"), 173);
    genres.insert(QLatin1String("nu breakz"), 174);
    genres.insert(QLatin1String("post punk"), 175);
    genres.insert(QLatin1String("post rock"), 176);
    genres.insert(QLatin1String("psytrance"), 177);
    genres.insert(QLatin1String("shoegaze"), 178);
    genres.insert(QLatin1String("space rock"), 179);
    genres.insert(QLatin1String("trop rock"), 180);
    genres.insert(QLatin1String("world music"), 181);
    genres.insert(QLatin1String("neoclassical"), 182);
    genres.insert(QLatin1String("audiobook"), 183);
    genres.insert(QLatin1String("audio theatre"), 184);
    genres.insert(QLatin1String("neue deutsche welle"), 185);
    genres.insert(QLatin1String("podcast"), 186);
    genres.insert(QLatin1String("indie rock"), 187);
    genres.insert(QLatin1String("g funk"), 188);
    genres.insert(QLatin1String("dubstep"), 189);
    genres.insert(QLatin1String("garage rock"), 190);
    genres.insert(QLatin1String("psybient"), 191);
}
