#include "id3_music_genres.h"

Id3MusicGenres * Id3MusicGenres::self = 0;

Id3MusicGenres * Id3MusicGenres::instance() {
    if(!self)
        self = new Id3MusicGenres();
    return self;
}

void Id3MusicGenres::initDefault() {
    genres.insert(QStringLiteral("blues"), 0);
    genres.insert(QStringLiteral("classic rock"), 1);
    genres.insert(QStringLiteral("country"), 2);
    genres.insert(QStringLiteral("dance"), 3);
    genres.insert(QStringLiteral("disco"), 4);
    genres.insert(QStringLiteral("funk"), 5);
    genres.insert(QStringLiteral("grunge"), 6);
    genres.insert(QStringLiteral("hip hop"), 7);
    genres.insert(QStringLiteral("jazz"), 8);
    genres.insert(QStringLiteral("metal"), 9);
    genres.insert(QStringLiteral("new age"), 10);
    genres.insert(QStringLiteral("oldies"), 11);
    genres.insert(QStringLiteral("other"), 12);
    genres.insert(QStringLiteral("pop"), 13);
    genres.insert(QStringLiteral("rhythm & blues"), 14);
    genres.insert(QStringLiteral("rhythm and blues"), 14);
    genres.insert(QStringLiteral("rap"), 15);
    genres.insert(QStringLiteral("reggae"), 16);
    genres.insert(QStringLiteral("rock"), 17);
    genres.insert(QStringLiteral("techno"), 18);
    genres.insert(QStringLiteral("industrial"), 19);
    genres.insert(QStringLiteral("alternative"), 20);
    genres.insert(QStringLiteral("ska"), 21);
    genres.insert(QStringLiteral("death metal"), 22);
    genres.insert(QStringLiteral("pranks"), 23);
    genres.insert(QStringLiteral("soundtrack"), 24);
    genres.insert(QStringLiteral("euro techno"), 25);
    genres.insert(QStringLiteral("ambient"), 26);
    genres.insert(QStringLiteral("trip hop"), 27);
    genres.insert(QStringLiteral("trip"), 27);
    genres.insert(QStringLiteral("vocal"), 28);
    genres.insert(QStringLiteral("jazz & funk"), 29);
    genres.insert(QStringLiteral("jazz and funk"), 29);
    genres.insert(QStringLiteral("fusion"), 30);
    genres.insert(QStringLiteral("trance"), 31);
    genres.insert(QStringLiteral("classical"), 32);
    genres.insert(QStringLiteral("instrumental"), 33);
    genres.insert(QStringLiteral("acid"), 34);
    genres.insert(QStringLiteral("house"), 35);
    genres.insert(QStringLiteral("game"), 36);
    genres.insert(QStringLiteral("sound clip"), 37);
    genres.insert(QStringLiteral("gospel"), 38);
    genres.insert(QStringLiteral("noise"), 39);
    genres.insert(QStringLiteral("alternative rock"), 40);
    genres.insert(QStringLiteral("bass"), 41);
    genres.insert(QStringLiteral("soul"), 42);
    genres.insert(QStringLiteral("punk"), 43);
    genres.insert(QStringLiteral("space"), 44);
    genres.insert(QStringLiteral("meditative"), 45);
    genres.insert(QStringLiteral("instrumental pop"), 46);
    genres.insert(QStringLiteral("instrumental rock"), 47);
    genres.insert(QStringLiteral("ethnic"), 48);
    genres.insert(QStringLiteral("gothic"), 49);
    genres.insert(QStringLiteral("darkwave"), 50);
    genres.insert(QStringLiteral("techno industrial"), 51);
    genres.insert(QStringLiteral("electronic"), 52);
    genres.insert(QStringLiteral("pop folk"), 53);
    genres.insert(QStringLiteral("eurodance"), 54);
    genres.insert(QStringLiteral("dream"), 55);
    genres.insert(QStringLiteral("southern rock"), 56);
    genres.insert(QStringLiteral("comedy"), 57);
    genres.insert(QStringLiteral("cult"), 58);
    genres.insert(QStringLiteral("gangsta"), 59);
    genres.insert(QStringLiteral("top 40"), 60);
    genres.insert(QStringLiteral("christian rap"), 61);
    genres.insert(QStringLiteral("pop funk"), 62);
    genres.insert(QStringLiteral("jungle"), 63);
    genres.insert(QStringLiteral("native american"), 64);
    genres.insert(QStringLiteral("cabaret"), 65);
    genres.insert(QStringLiteral("new wave"), 66);
    genres.insert(QStringLiteral("psychedelic"), 67);
    genres.insert(QStringLiteral("rave"), 68);
    genres.insert(QStringLiteral("showtunes"), 69);
    genres.insert(QStringLiteral("trailer"), 70);
    genres.insert(QStringLiteral("lo fi"), 71);
    genres.insert(QStringLiteral("tribal"), 72);
    genres.insert(QStringLiteral("acid punk"), 73);
    genres.insert(QStringLiteral("acid jazz"), 74);
    genres.insert(QStringLiteral("polka"), 75);
    genres.insert(QStringLiteral("retro"), 76);
    genres.insert(QStringLiteral("musical"), 77);
    genres.insert(QStringLiteral("rock & roll"), 78);
    genres.insert(QStringLiteral("rock and roll"), 78);
    genres.insert(QStringLiteral("hard rock"), 79);
    genres.insert(QStringLiteral("folk"), 80);
    genres.insert(QStringLiteral("folk rock"), 81);
    genres.insert(QStringLiteral("national folk"), 82);
    genres.insert(QStringLiteral("swing"), 83);
    genres.insert(QStringLiteral("fast fusion"), 84);
    genres.insert(QStringLiteral("bebop"), 85);
    genres.insert(QStringLiteral("latin"), 86);
    genres.insert(QStringLiteral("revival"), 87);
    genres.insert(QStringLiteral("celtic"), 88);
    genres.insert(QStringLiteral("bluegrass"), 89);
    genres.insert(QStringLiteral("avantgarde"), 90);
    genres.insert(QStringLiteral("gothic rock"), 91);
    genres.insert(QStringLiteral("progressive rock"), 92);
    genres.insert(QStringLiteral("psychedelic rock"), 93);
    genres.insert(QStringLiteral("symphonic rock"), 94);
    genres.insert(QStringLiteral("slow rock"), 95);
    genres.insert(QStringLiteral("big band"), 96);
    genres.insert(QStringLiteral("chorus"), 97);
    genres.insert(QStringLiteral("easy listening"), 98);
    genres.insert(QStringLiteral("acoustic"), 99);
    genres.insert(QStringLiteral("humour"), 100);
    genres.insert(QStringLiteral("speech"), 101);
    genres.insert(QStringLiteral("chanson"), 102);
    genres.insert(QStringLiteral("opera"), 103);
    genres.insert(QStringLiteral("chamber music"), 104);
    genres.insert(QStringLiteral("sonata"), 105);
    genres.insert(QStringLiteral("symphony"), 106);
    genres.insert(QStringLiteral("booty bass"), 107);
    genres.insert(QStringLiteral("primus"), 108);
    genres.insert(QStringLiteral("porn groove"), 109);
    genres.insert(QStringLiteral("satire"), 110);
    genres.insert(QStringLiteral("slow jam"), 111);
    genres.insert(QStringLiteral("club"), 112);
    genres.insert(QStringLiteral("tango"), 113);
    genres.insert(QStringLiteral("samba"), 114);
    genres.insert(QStringLiteral("folklore"), 115);
    genres.insert(QStringLiteral("ballad"), 116);
    genres.insert(QStringLiteral("power ballad"), 117);
    genres.insert(QStringLiteral("rhythmic soul"), 118);
    genres.insert(QStringLiteral("freestyle"), 119);
    genres.insert(QStringLiteral("duet"), 120);
    genres.insert(QStringLiteral("punk rock"), 121);
    genres.insert(QStringLiteral("drum solo"), 122);
    genres.insert(QStringLiteral("a capella"), 123);
    genres.insert(QStringLiteral("acapella"), 123);
    genres.insert(QStringLiteral("euro house"), 124);
    genres.insert(QStringLiteral("dance hall"), 125);
    genres.insert(QStringLiteral("goa"), 126);
    genres.insert(QStringLiteral("drum & bass"), 127);
    genres.insert(QStringLiteral("drum and bass"), 127);
    genres.insert(QStringLiteral("club house"), 128);
    genres.insert(QStringLiteral("hardcore techno"), 129);
    genres.insert(QStringLiteral("terror"), 130);
    genres.insert(QStringLiteral("indie"), 131);
    genres.insert(QStringLiteral("britPop"), 132);
    genres.insert(QStringLiteral("afro punk"), 133);
    genres.insert(QStringLiteral("polsk punk"), 134);
    genres.insert(QStringLiteral("beat"), 135);
    genres.insert(QStringLiteral("christian gangsta rap"), 136);
    genres.insert(QStringLiteral("heavy metal"), 137);
    genres.insert(QStringLiteral("black metal"), 138);
    genres.insert(QStringLiteral("crossover"), 139);
    genres.insert(QStringLiteral("contemporary christian"), 140);
    genres.insert(QStringLiteral("christian rock"), 141);
    genres.insert(QStringLiteral("merengue"), 142);
    genres.insert(QStringLiteral("salsa"), 143);
    genres.insert(QStringLiteral("thrash metal"), 144);
    genres.insert(QStringLiteral("anime"), 145);
    genres.insert(QStringLiteral("jpop"), 146);
    genres.insert(QStringLiteral("synthpop"), 147);
    genres.insert(QStringLiteral("abstract"), 148);
    genres.insert(QStringLiteral("art rock"), 149);
    genres.insert(QStringLiteral("baroque"), 150);
    genres.insert(QStringLiteral("bhangra"), 151);
    genres.insert(QStringLiteral("big beat"), 152);
    genres.insert(QStringLiteral("breakbeat"), 153);
    genres.insert(QStringLiteral("chillout"), 154);
    genres.insert(QStringLiteral("downtempo"), 155);
    genres.insert(QStringLiteral("dub"), 156);
    genres.insert(QStringLiteral("ebm"), 157);
    genres.insert(QStringLiteral("eclectic"), 158);
    genres.insert(QStringLiteral("electro"), 159);
    genres.insert(QStringLiteral("electroclash"), 160);
    genres.insert(QStringLiteral("emo"), 161);
    genres.insert(QStringLiteral("experimental"), 162);
    genres.insert(QStringLiteral("garage"), 163);
    genres.insert(QStringLiteral("global"), 164);
    genres.insert(QStringLiteral("idm"), 165);
    genres.insert(QStringLiteral("illbient"), 166);
    genres.insert(QStringLiteral("industro Goth"), 167);
    genres.insert(QStringLiteral("jam band"), 168);
    genres.insert(QStringLiteral("krautrock"), 169);
    genres.insert(QStringLiteral("leftfield"), 170);
    genres.insert(QStringLiteral("lounge"), 171);
    genres.insert(QStringLiteral("math rock"), 172);
    genres.insert(QStringLiteral("new romantic"), 173);
    genres.insert(QStringLiteral("nu breakz"), 174);
    genres.insert(QStringLiteral("post punk"), 175);
    genres.insert(QStringLiteral("post rock"), 176);
    genres.insert(QStringLiteral("psytrance"), 177);
    genres.insert(QStringLiteral("shoegaze"), 178);
    genres.insert(QStringLiteral("space rock"), 179);
    genres.insert(QStringLiteral("trop rock"), 180);
    genres.insert(QStringLiteral("world music"), 181);
    genres.insert(QStringLiteral("neoclassical"), 182);
    genres.insert(QStringLiteral("audiobook"), 183);
    genres.insert(QStringLiteral("audio theatre"), 184);
    genres.insert(QStringLiteral("neue deutsche welle"), 185);
    genres.insert(QStringLiteral("podcast"), 186);
    genres.insert(QStringLiteral("indie rock"), 187);
    genres.insert(QStringLiteral("g funk"), 188);
    genres.insert(QStringLiteral("dubstep"), 189);
    genres.insert(QStringLiteral("garage rock"), 190);
    genres.insert(QStringLiteral("psybient"), 191);
}
