#include "music_genres.h"

MusicGenres * MusicGenres::self = 0;

MusicGenres * MusicGenres::instance() {
    if(!self)
        self = new MusicGenres();
    return self;
}

void MusicGenres::initDefault() {
    genres.insert(0,   "Blues");
    genres.insert(1,   "Classic Rock");
    genres.insert(2,   "Country");
    genres.insert(3,   "Dance");
    genres.insert(4,   "Disco");
    genres.insert(5,   "Funk");
    genres.insert(6,   "Grunge");
    genres.insertMulti(7,   "Hip-Hop");
    genres.insertMulti(7,   "HipHop");

    genres.insert(8,   "Jazz");
    genres.insert(9,   "Metal");
    genres.insert(10,  "New Age");
    genres.insert(11,  "Oldies");
    genres.insert(12,  "Other");
    genres.insert(13,  "Pop");
    genres.insert(14,  "Rhythm and Blues");
    genres.insert(15,  "Rap");
    genres.insert(16,  "Reggae");
    genres.insert(17,  "Rock");
    genres.insert(18,  "Techno");
    genres.insert(19,  "Industrial");
    genres.insert(20,  "Alternative");
    genres.insert(21,  "Ska");
    genres.insert(22,  "Death Metal");
    genres.insert(23,  "Pranks");
    genres.insert(24,  "Soundtrack");
    genres.insert(25,  "Euro-Techno");
    genres.insert(26,  "Ambient");
    genres.insertMulti(27,  "Trip-Hop");
    genres.insertMulti(27,  "TripHop");
    genres.insertMulti(27,  "Trip");
    genres.insert(28,  "Vocal");
    genres.insert(29,  "Jazz & Funk");
    genres.insert(30,  "Fusion");
    genres.insert(31,  "Trance");
    genres.insert(32,  "Classical");
    genres.insert(33,  "Instrumental");
    genres.insert(34,  "Acid");
    genres.insert(35,  "House");
    genres.insert(36,  "Game");
    genres.insert(37,  "Sound Clip");
    genres.insert(38,  "Gospel");
    genres.insert(39,  "Noise");
    genres.insert(40,  "Alternative Rock");
    genres.insert(41,  "Bass");
    genres.insert(42,  "Soul");
    genres.insert(43,  "Punk");
    genres.insert(44,  "Space");
    genres.insert(45,  "Meditative");
    genres.insert(46,  "Instrumental Pop");
    genres.insert(47,  "Instrumental Rock");
    genres.insert(48,  "Ethnic");
    genres.insert(49,  "Gothic");
    genres.insert(50,  "Darkwave");
    genres.insert(51,  "Techno-Industrial");
    genres.insert(52,  "Electronic");
    genres.insert(53,  "Pop-Folk");
    genres.insert(54,  "Eurodance");
    genres.insert(55,  "Dream");
    genres.insert(56,  "Southern Rock");
    genres.insert(57,  "Comedy");
    genres.insert(58,  "Cult");
    genres.insert(59,  "Gangsta");
    genres.insert(60,  "Top 40");
    genres.insert(61,  "Christian Rap");
    genres.insert(62,  "Pop/Funk");
    genres.insert(63,  "Jungle");
    genres.insert(64,  "Native American");
    genres.insert(65,  "Cabaret");
    genres.insert(66,  "New Wave");
    genres.insert(67,  "Psychedelic");
    genres.insert(68,  "Rave");
    genres.insert(69,  "Showtunes");
    genres.insert(70,  "Trailer");
    genres.insert(71,  "Lo-Fi");
    genres.insert(72,  "Tribal");
    genres.insert(73,  "Acid Punk");
    genres.insert(74,  "Acid Jazz");
    genres.insert(75,  "Polka");
    genres.insert(76,  "Retro");
    genres.insert(77,  "Musical");
    genres.insert(78,  "Rock & Roll");
    genres.insert(79,  "Hard Rock");
    genres.insert(80,  "Folk");
    genres.insert(81,  "Folk-Rock");
    genres.insert(82,  "National Folk");
    genres.insert(83,  "Swing");
    genres.insert(84,  "Fast Fusion");
    genres.insert(85,  "Bebop");
    genres.insert(86,  "Latin");
    genres.insert(87,  "Revival");
    genres.insert(88,  "Celtic");
    genres.insert(89,  "Bluegrass");
    genres.insert(90,  "Avantgarde");
    genres.insert(91,  "Gothic Rock");
    genres.insert(92,  "Progressive Rock");
    genres.insert(93,  "Psychedelic Rock");
    genres.insert(94,  "Symphonic Rock");
    genres.insert(95,  "Slow Rock");
    genres.insert(96,  "Big Band");
    genres.insert(97,  "Chorus");
    genres.insert(98,  "Easy Listening");
    genres.insert(99,  "Acoustic");
    genres.insert(100, "Humour");
    genres.insert(101, "Speech");
    genres.insert(102, "Chanson");
    genres.insert(103, "Opera");
    genres.insert(104, "Chamber Music");
    genres.insert(105, "Sonata");
    genres.insert(106, "Symphony");
    genres.insert(107, "Booty Bass");
    genres.insert(108, "Primus");
    genres.insert(109, "Porn groove");
    genres.insert(110, "Satire");
    genres.insert(111, "Slow Jam");
    genres.insert(112, "Club");
    genres.insert(113, "Tango");
    genres.insert(114, "Samba");
    genres.insert(115, "Folklore");
    genres.insert(116, "Ballad");
    genres.insert(117, "Power Ballad");
    genres.insert(118, "Rhythmic Soul");
    genres.insert(119, "Freestyle");
    genres.insert(120, "Duet");
    genres.insert(121, "Punk Rock");
    genres.insert(122, "Drum Solo");
    genres.insert(123, "A capella");
    genres.insert(124, "Euro-House");
    genres.insert(125, "Dance Hall");
    genres.insert(126, "Goa");
    genres.insert(127, "Drum & Bass");
    genres.insert(128, "Club-House");
    genres.insert(129, "Hardcore Techno");
    genres.insert(130, "Terror");
    genres.insert(131, "Indie");
    genres.insert(132, "BritPop");
    genres.insert(133, "Afro-punk");
    genres.insert(134, "Polsk Punk");
    genres.insert(135, "Beat");
    genres.insert(136, "Christian Gangsta Rap");
    genres.insert(137, "Heavy Metal");
    genres.insert(138, "Black Metal");
    genres.insert(139, "Crossover");
    genres.insert(140, "Contemporary Christian");
    genres.insert(141, "Christian Rock");
    genres.insert(142, "Merengue");
    genres.insert(143, "Salsa");
    genres.insert(144, "Thrash Metal");
    genres.insert(145, "Anime");
    genres.insert(146, "Jpop");
    genres.insert(147, "Synthpop");
    genres.insert(148, "Abstract");
    genres.insert(149, "Art Rock");
    genres.insert(150, "Baroque");
    genres.insert(151, "Bhangra");
    genres.insert(152, "Big Beat");
    genres.insert(153, "Breakbeat");
    genres.insert(154, "Chillout");
    genres.insert(155, "Downtempo");
    genres.insert(156, "Dub");
    genres.insert(157, "EBM");
    genres.insert(158, "Eclectic");
    genres.insert(159, "Electro");
    genres.insert(160, "Electroclash");
    genres.insert(161, "Emo");
    genres.insert(162, "Experimental");
    genres.insert(163, "Garage");
    genres.insert(164, "Global");
    genres.insert(165, "IDM");
    genres.insert(166, "Illbient");
    genres.insert(167, "Industro-Goth");
    genres.insert(168, "Jam Band");
    genres.insert(169, "Krautrock");
    genres.insert(170, "Leftfield");
    genres.insert(171, "Lounge");
    genres.insert(172, "Math Rock");
    genres.insert(173, "New Romantic");
    genres.insert(174, "Nu-Breakz");
    genres.insert(175, "Post-Punk");
    genres.insert(176, "Post-Rock");
    genres.insert(177, "Psytrance");
    genres.insert(178, "Shoegaze");
    genres.insert(179, "Space Rock");
    genres.insert(180, "Trop Rock");
    genres.insert(181, "World Music");
    genres.insert(182, "Neoclassical");
    genres.insert(183, "Audiobook");
    genres.insert(184, "Audio Theatre");
    genres.insert(185, "Neue Deutsche Welle");
    genres.insert(186, "Podcast");
    genres.insert(187, "Indie Rock");
    genres.insert(188, "G-Funk");
    genres.insert(189, "Dubstep");
    genres.insert(190, "Garage Rock");
    genres.insert(191, "Psybient");
}
