#include "music_genres.h"

MusicGenres * MusicGenres::self = 0;

MusicGenres * MusicGenres::instance() {
    if(!self)
        self = new MusicGenres();
    return self;
}

void MusicGenres::initDefault() {
    genres.insert("Blues", 0);
    genres.insert("Classic Rock", 1);
    genres.insert("Country", 2);
    genres.insert("Dance", 3);
    genres.insert("Disco", 4);
    genres.insert("Funk", 5);
    genres.insert("Grunge", 6);
    genres.insert("Hip-Hop", 7);
    genres.insert("HipHop", 7);
    genres.insert("Jazz", 8);
    genres.insert("Metal", 9);
    genres.insert("New Age", 10);
    genres.insert("NewAge", 10);
    genres.insert("Oldies", 11);
    genres.insert("Other", 12);
    genres.insert("Pop", 13);
    genres.insert("Rhythm and Blues", 14);
    genres.insert("Rhythm & Blues", 14);
    genres.insert("Rap", 15);
    genres.insert("Reggae", 16);
    genres.insert("Rock", 17);
    genres.insert("Techno", 18);
    genres.insert("Industrial", 19);
    genres.insert("Alternative", 20);
    genres.insert("Ska", 21);
    genres.insert("Death Metal", 22);
    genres.insert("DeathMetal", 22);
    genres.insert("Pranks", 23);
    genres.insert("Soundtrack", 24);
    genres.insert("Euro-Techno", 25);
    genres.insert("EuroTechno", 25);
    genres.insert("Ambient", 26);
    genres.insert("Trip-Hop", 27);
    genres.insert("TripHop", 27);
    genres.insert("Trip", 27);
    genres.insert("Vocal", 28);
    genres.insert("Jazz&Funk", 29);
    genres.insert("Jazz & Funk", 29);
    genres.insert("Jazz and Funk", 29);
    genres.insert("Fusion", 30);
    genres.insert("Trance", 31);
    genres.insert("Classical", 32);
    genres.insert("Instrumental", 33);
    genres.insert("Acid", 34);
    genres.insert("House", 35);
    genres.insert("Game", 36);
    genres.insert("Sound Clip", 37);
    genres.insert("Gospel", 38);
    genres.insert("Noise", 39);
    genres.insert("Alternative Rock", 40);
    genres.insert("AlternativeRock", 40);
    genres.insert("Bass", 41);
    genres.insert("Soul", 42);
    genres.insert("Punk", 43);
    genres.insert("Space", 44);
    genres.insert("Meditative", 45);
    genres.insert("Instrumental Pop", 46);
    genres.insert("InstrumentalPop", 46);
    genres.insert("Instrumental Rock", 47);
    genres.insert("InstrumentalRock", 47);
    genres.insert("Ethnic", 48);
    genres.insert("Gothic", 49);
    genres.insert("Darkwave", 50);
    genres.insert("Techno-Industrial", 51);
    genres.insert("TechnoIndustrial", 51);
    genres.insert("Techno Industrial", 51);
    genres.insert("Electronic", 52);
    genres.insert("Pop-Folk", 53);
    genres.insert("PopFolk", 53);
    genres.insert("Pop Folk", 53);
    genres.insert("Eurodance", 54);
    genres.insert("Dream", 55);
    genres.insert("Southern Rock", 56);
    genres.insert("Comedy", 57);
    genres.insert("Cult", 58);
    genres.insert("Gangsta", 59);
    genres.insert("Top 40", 60);
    genres.insert("Top40", 60);
    genres.insert("Christian Rap", 61);
    genres.insert("Pop/Funk", 62);
    genres.insert("Pop-Funk", 62);
    genres.insert("PopFunk", 62);
    genres.insert("Jungle", 63);
    genres.insert("Native American", 64);
    genres.insert("Cabaret", 65);
    genres.insert("New Wave", 66);
    genres.insert("NewWave", 66);
    genres.insert("Psychedelic", 67);
    genres.insert("Rave", 68);
    genres.insert("Showtunes", 69);
    genres.insert("Trailer", 70);
    genres.insert("Lo-Fi", 71);
    genres.insert("LoFi", 71);
    genres.insert("Lo Fi", 71);
    genres.insert("Tribal", 72);
    genres.insert("Acid Punk", 73);
    genres.insert("AcidPunk", 73);
    genres.insert("AcidJazz", 74);
    genres.insert("Acid Jazz", 74);
    genres.insert("Polka", 75);
    genres.insert("Retro", 76);
    genres.insert("Musical", 77);
    genres.insert("Rock & Roll", 78);
    genres.insert("Rock&Roll", 78);
    genres.insert("Rock and Roll", 78);
    genres.insert("Hard Rock", 79);
    genres.insert("Folk", 80);
    genres.insert("Folk-Rock", 81);
    genres.insert("Folk Rock", 81);
    genres.insert("FolkRock", 81);
    genres.insert("National Folk", 82);
    genres.insert("Swing", 83);
    genres.insert("Fast Fusion", 84);
    genres.insert("Bebop", 85);
    genres.insert("Latin", 86);
    genres.insert("Revival", 87);
    genres.insert("Celtic", 88);
    genres.insert("Bluegrass", 89);
    genres.insert("Avantgarde", 90);
    genres.insert("Gothic Rock", 91);
    genres.insert("Progressive Rock", 92);
    genres.insert("Psychedelic Rock", 93);
    genres.insert("Symphonic Rock", 94);
    genres.insert("Slow Rock", 95);
    genres.insert("Big Band", 96);
    genres.insert("Chorus", 97);
    genres.insert("Easy Listening", 98);
    genres.insert("Acoustic", 99);
    genres.insert("Humour", 100);
    genres.insert(101, "Speech");
    genres.insert(102, "Chanson");
    genres.insert(103, "Opera");
    genres.insert(104, "Chamber Music");
    genres.insert(105, "Sonata");
    genres.insert(106, "Symphony");
    genres.insert(107, "Booty Bass");
    genres.insert(108, "Primus");
    genres.insert(109, "Porn groove");
    genres.insert(110, "Satire");
    genres.insert(111, "Slow Jam");
    genres.insert(112, "Club");
    genres.insert(113, "Tango");
    genres.insert(114, "Samba");
    genres.insert(115, "Folklore");
    genres.insert(116, "Ballad");
    genres.insert(117, "Power Ballad");
    genres.insert(118, "Rhythmic Soul");
    genres.insert(119, "Freestyle");
    genres.insert(120, "Duet");
    genres.insert(121, "Punk Rock");
    genres.insert(122, "Drum Solo");
    genres.insert(123, "A capella");
    genres.insert(124, "Euro-House");
    genres.insert(125, "Dance Hall");
    genres.insert(126, "Goa");
    genres.insert(127, "Drum & Bass");
    genres.insert(128, "Club-House");
    genres.insert(129, "Hardcore Techno");
    genres.insert(130, "Terror");
    genres.insert(131, "Indie");
    genres.insert(132, "BritPop");
    genres.insert(133, "Afro-punk");
    genres.insert(134, "Polsk Punk");
    genres.insert(135, "Beat");
    genres.insert(136, "Christian Gangsta Rap");
    genres.insert(137, "Heavy Metal");
    genres.insert(138, "Black Metal");
    genres.insert(139, "Crossover");
    genres.insert(140, "Contemporary Christian");
    genres.insert(141, "Christian Rock");
    genres.insert(142, "Merengue");
    genres.insert(143, "Salsa");
    genres.insert(144, "Thrash Metal");
    genres.insert(145, "Anime");
    genres.insert(146, "Jpop");
    genres.insert(147, "Synthpop");
    genres.insert(148, "Abstract");
    genres.insert(149, "Art Rock");
    genres.insert(150, "Baroque");
    genres.insert(151, "Bhangra");
    genres.insert(152, "Big Beat");
    genres.insert(153, "Breakbeat");
    genres.insert(154, "Chillout");
    genres.insert(155, "Downtempo");
    genres.insert(156, "Dub");
    genres.insert(157, "EBM");
    genres.insert(158, "Eclectic");
    genres.insert(159, "Electro");
    genres.insert(160, "Electroclash");
    genres.insert(161, "Emo");
    genres.insert(162, "Experimental");
    genres.insert(163, "Garage");
    genres.insert(164, "Global");
    genres.insert(165, "IDM");
    genres.insert(166, "Illbient");
    genres.insert(167, "Industro-Goth");
    genres.insert(168, "Jam Band");
    genres.insert(169, "Krautrock");
    genres.insert(170, "Leftfield");
    genres.insert(171, "Lounge");
    genres.insert(172, "Math Rock");
    genres.insert(173, "New Romantic");
    genres.insert(174, "Nu-Breakz");
    genres.insert(175, "Post-Punk");
    genres.insert(176, "Post-Rock");
    genres.insert(177, "Psytrance");
    genres.insert(178, "Shoegaze");
    genres.insert(179, "Space Rock");
    genres.insert(180, "Trop Rock");
    genres.insert(181, "World Music");
    genres.insert(182, "Neoclassical");
    genres.insert(183, "Audiobook");
    genres.insert(184, "Audio Theatre");
    genres.insert(185, "Neue Deutsche Welle");
    genres.insert(186, "Podcast");
    genres.insert(187, "Indie Rock");
    genres.insert(188, "G-Funk");
    genres.insert(189, "Dubstep");
    genres.insert(190, "Garage Rock");
    genres.insert(191, "Psybient");
}
